#!/bin/bash

echo "🔍 COMPREHENSIVE FRONTEND-BACKEND ENDPOINT ANALYSIS"
echo "=================================================="

echo ""
echo "📱 FRONTEND API CALLS (from useUnifiedBackend.js):"
echo "---------------------------------------------------"
grep -o "apiCall('[^']*'" src/useUnifiedBackend.js | sort | uniq | sed "s/apiCall('//g" | sed "s/'//g"

echo ""
echo "🖥️  BACKEND API ENDPOINTS (from Controllers):"
echo "-----------------------------------------------"

echo "Health Controller [/api/health]:"
echo "  GET  /api/health"

echo ""
echo "Users Controller [/api/users]:"
echo "  POST /api/users/register"
echo "  POST /api/users/login"
echo "  GET  /api/users"
echo "  POST /api/users/join/{code}"
echo "  GET  /api/users/{userId}/state"
echo "  PUT  /api/users/{userId}/presence"
echo "  POST /api/users/{userId}/offline"

echo ""
echo "Game Controller [/api/game]:"
echo "  POST /api/game/sessions"
echo "  GET  /api/game/sessions/{sessionId}"
echo "  GET  /api/game/sessions/couple/{coupleId}"
echo "  POST /api/game/couples"
echo "  GET  /api/game/couples"
echo "  POST /api/game/couples/by-code"
echo "  POST /api/game/couples/switch"
echo "  POST /api/game/couples/{coupleId}/join"
echo "  POST /api/game/couples/leave"
echo "  GET  /api/game/couples/user/{userId}"
echo "  GET  /api/game/couples/{coupleId}/sessions"
echo "  GET  /api/game/couples/{coupleId}"
echo "  GET  /api/game/cards/{gameType}"
echo "  GET  /api/game/cards/{gameType}/random"
echo "  POST /api/game/create-couple"
echo "  POST /api/game/join-couple"
echo "  POST /api/game/leave-couple"
echo "  POST /api/game/start-session"
echo "  POST /api/game/sessions/{sessionId}/end"

echo ""
echo "Admin Controller [/api/admin]:"
echo "  POST /api/admin/clear-users"
echo "  POST /api/admin/reset-system"
echo "  POST /api/admin/force-refresh"

echo ""
echo "🚨 POTENTIAL ENDPOINT MISMATCHES:"
echo "-------------------------"

