name: CI E2E

on:
  workflow_dispatch:
  push:
    branches: [ Evolution ]
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'package.json'
      - 'playwright.config.*'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore & Build Backend
        working-directory: Backend/ComplicityGame.Api
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: Run Backend
        working-directory: Backend/ComplicityGame.Api
        run: |
          dotnet run --configuration Release --no-build &
          echo $! > backend.pid
      - name: Wait for Backend Health
        run: |
          echo "Probing backend health endpoint...";
          for i in {1..60}; do
            STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' http://localhost:5000/api/health || true)
            if [ "$STATUS" = "200" ]; then
              echo "Health OK (HTTP 200) at attempt $i";
              curl -fsS http://localhost:5000/api/health || true
              exit 0;
            fi
            if ! ps -p $(cat Backend/ComplicityGame.Api/backend.pid) > /dev/null 2>&1; then
              echo "Backend process exited prematurely"; break; fi
            if [ $((i % 10)) -eq 0 ]; then
              echo "Attempt $i still waiting (last status: $STATUS)";
            fi
            sleep 1;
          done
          echo "--- Backend logs (last 200 lines) ---" || true
          ls -1 Backend/ComplicityGame.Api || true
          echo "Failing due to backend not healthy"; exit 1
      - name: Run E2E
        env:
          CI: true
        run: npm run test:e2e
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
      - name: Stop Backend
        if: always()
        run: |
          if [ -f Backend/ComplicityGame.Api/backend.pid ]; then kill $(cat Backend/ComplicityGame.Api/backend.pid) || true; fi
