name: CI E2E

on:
  workflow_dispatch:
  push:
    branches: [ Evolution ]
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'package.json'
      - 'playwright.config.*'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Backend (placeholder)
        run: |
          echo "Avvia backend esterno prima di eseguire questi test se necessario" \
            && echo "Se esiste script npm backend aggiungerlo qui"
      - name: Run E2E
        env:
          CI: true
        run: npm run test:e2e
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
