name: Verify (Lint + Unit + Smoke)

on:
  pull_request:
    branches: [ Evolution ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'playwright.config.*'
      - 'vitest.config.*'
  push:
    branches: [ Evolution ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'playwright.config.*'
      - 'vitest.config.*'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Run consolidated verify script
        run: |
          if npm run | grep -q "verify"; then npm run verify; else echo "No verify script found"; fi
      - name: Setup .NET (backend for smoke tests)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Backend
        working-directory: Backend/ComplicityGame.Api
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: Run Backend
        working-directory: Backend/ComplicityGame.Api
        run: |
          dotnet run --configuration Release --no-build > backend.log 2>&1 &
          echo $! > backend.pid
      - name: Wait for Backend Health
        run: |
          for i in {1..40}; do
            STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' http://localhost:5000/api/health || true)
            if [ "$STATUS" = "200" ]; then echo "Health OK"; exit 0; fi
            sleep 1;
          done
          echo "Backend not healthy"; exit 1
      - name: Smoke E2E (join + reconnect + approve subset)
        env:
          CI: true
        run: npm run test:e2e:smoke --if-present
      - name: Upload Playwright Smoke Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-smoke-report
          path: playwright-report
          if-no-files-found: ignore
      - name: Upload backend log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-log
          path: Backend/ComplicityGame.Api/backend.log
          if-no-files-found: ignore
      - name: Stop Backend
        if: always()
        run: |
          if [ -f Backend/ComplicityGame.Api/backend.pid ]; then kill $(cat Backend/ComplicityGame.Api/backend.pid) || true; fi